config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  resources :doctors
  resources :preservices
  resources :patients
  devise_for :users

  root to: 'index#menu'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/preservice.rb
class Preservice < ApplicationRecord
  belongs_to :user
  belongs_to :patient
end

app/controllers/preservices_controller.rb
class PreservicesController < ApplicationController
  before_action :set_preservice, only: [:show, :edit, :update, :destroy]

  # GET /preservices
  # GET /preservices.json
  def index
    @preservices = Preservice.all.includes(:patient)
  end

  # GET /preservices/1
  # GET /preservices/1.json
  def show
  end

  # GET /preservices/new
  def new
    @preservice = current_user.preservices.new
  end

  # GET /preservices/1/edit
  def edit
  end

  # POST /preservices
  # POST /preservices.json
  def create
    @preservice = current_user.preservices.new(preservice_params)

    respond_to do |format|
      if @preservice.save
        format.html { redirect_to @preservice, notice: 'Preservice was successfully created.' }
        format.json { render :show, status: :created, location: @preservice }
      else
        format.html { render :new }
        format.json { render json: @preservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /preservices/1
  # PATCH/PUT /preservices/1.json
  def update
    respond_to do |format|
      if @preservice.update(preservice_params)
        format.html { redirect_to @preservice, notice: 'Preservice was successfully updated.' }
        format.json { render :show, status: :ok, location: @preservice }
      else
        format.html { render :edit }
        format.json { render json: @preservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preservices/1
  # DELETE /preservices/1.json
  def destroy
    @preservice.destroy
    respond_to do |format|
      format.html { redirect_to preservices_url, notice: 'Preservice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preservice
      @preservice = current_user.preservices.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preservice_params
      params.require(:preservice).permit(:type_service, :note, :reasons, :situation, :user_id, :patient_id)
    end
end

app/helpers/preservices_helper.rb
module PreservicesHelper
end

app/views/preservices/_form.html.erb
<%= form_with(model: preservice, local: true) do |form| %>
  <% if preservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(preservice.errors.count, "error") %> prohibited this preservice from being saved:</h2>

      <ul>
      <% preservice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :type_service %>
    <%= form.text_field :type_service, id: :preservice_type_service, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, id: :preservice_note, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :reasons %>
    <%= form.text_area :reasons, id: :preservice_reasons, class:'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :situation %>
    <%= form.text_field :situation, id: :preservice_situation, class:'form-control' %>
  </div>

  <div class="form-group>
    <%= form.label :patient_id %>
    <%= form.collection_select :patient_id, Patient.all, :id, :name, prompt: true %>
  </div>
<br>
  <div class="actions">
    <button class="btn btn-primary" type="submit">Cadastrar Pré serviço</button>
  </div>
<% end %>

app/views/preservices/edit.html.erb
<h1>Editing Preservice</h1>

<%= render 'form', preservice: @preservice %>

<%= link_to 'Show', @preservice %> |
<%= link_to 'Back', preservices_path %>

app/views/preservices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Preservices</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="success">Type service</th>
      <th class="success">Note</th>
      <th class="success">Reasons</th>
      <th class="success">Situation</th>
      <th class="info">User</th>
      <th class="info">Patient</th>
      <th colspan="3" class="active"></th>
    </tr>
  </thead>

  <tbody>
    <% @preservices.each do |preservice| %>
      <tr>
        <td><%= preservice.type_service %></td>
        <td><%= preservice.note %></td>
        <td><%= preservice.reasons %></td>
        <td><%= preservice.situation %></td>
        <td><%= preservice.user.email %></td>
        <td><%= preservice.patient.name %></td>
        <td><%= link_to 'Show', preservice %></td>
        <td><%= link_to 'Edit', edit_preservice_path(preservice) %></td>
        <td><%= link_to 'Destroy', preservice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preservice', new_preservice_path %>

app/views/preservices/new.html.erb
<h1>New Preservice</h1>

<%= render 'form', preservice: @preservice %>
<br>
<%= link_to 'Back', preservices_path, class: "btn btn-danger" %>

app/views/preservices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type service:</strong>
  <%= @preservice.type_service %>
</p>

<p>
  <strong>Note:</strong>
  <%= @preservice.note %>
</p>

<p>
  <strong>Reasons:</strong>
  <%= @preservice.reasons %>
</p>

<p>
  <strong>Situation:</strong>
  <%= @preservice.situation %>
</p>

<p>
  <strong>User:</strong>
  <%= @preservice.user %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @preservice.patient %>
</p>

<%= link_to 'Edit', edit_preservice_path(@preservice) %> |
<%= link_to 'Back', preservices_path %>