config/routes.rb
Rails.application.routes.draw do
  resources :consultations
  resources :doctors
  resources :preservices
  resources :patients
  devise_for :users

  root to: 'index#menu'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/consultation.rb
class Consultation < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
  before_action :set_consultation, only: [:show, :edit, :update, :destroy]

  # GET /consultations
  # GET /consultations.json
  def index
    @consultations = Consultation.all
  end

  # GET /consultations/1
  # GET /consultations/1.json
  def show
  end

  # GET /consultations/new
  def new
    @consultation = Consultation.new
  end

  # GET /consultations/1/edit
  def edit
  end

  # POST /consultations
  # POST /consultations.json
  def create
    @consultation = Consultation.new(consultation_params)

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to @consultation, notice: 'Consultation was successfully created.' }
        format.json { render :show, status: :created, location: @consultation }
      else
        format.html { render :new }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultations/1
  # PATCH/PUT /consultations/1.json
  def update
    respond_to do |format|
      if @consultation.update(consultation_params)
        format.html { redirect_to @consultation, notice: 'Consultation was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultation }
      else
        format.html { render :edit }
        format.json { render json: @consultation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultations/1
  # DELETE /consultations/1.json
  def destroy
    @consultation.destroy
    respond_to do |format|
      format.html { redirect_to consultations_url, notice: 'Consultation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultation_params
      params.require(:consultation).permit(:historic, :note, :payment, :status, :doctor_id, :patient_id)
    end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/views/consultations/_form.html.erb
<%= form_with(model: consultation, local: true) do |form| %>
  <% if consultation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>

      <ul>
      <% consultation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :historic %>
    <%= form.text_area :historic, id: :consultation_historic, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :note %>
    <%= form.text_area :note, id: :consultation_note,  class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :payment %>
    <%= form.text_field :payment, id: :consultation_payment, class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.text_area :status, id: :consultation_status,  class:'form-control'%>
  </div>

  <div class="form-group">
    <%= form.label :doctor_id %>
    <%= form.collection_select :doctor_id, Doctor.all, :id, :name, prompt: true %>
    <!-- <%= form.text_field :doctor_id, id: :consultation_doctor_id %> -->
  </div>

  <div class="form-group">
    <%= form.label :patient_id %>
    <%= form.collection_select :patient_id, Patient.all, :id, :name, prompt: true %>
    <!-- <%= form.text_field :patient_id, id: :consultation_patient_id %> -->
  </div>

  <div class="actions">
    <button class="btn btn-primary" type="submit">Cadastrar Consulta</button>
  </div>
<% end %>

app/views/consultations/edit.html.erb
<h1>Editing Consultation</h1>

<%= render 'form', consultation: @consultation %>

<%= link_to 'Show', @consultation %> |
<%= link_to 'Back', consultations_path %>

app/views/consultations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Consultations</h1>

<table class="table table-hover table-bordered">
  <thead>
    <tr>
      <th class="success">Historic</th>
      <th class="success">Note</th>
      <th class="success">Payment</th>
      <th class="success">Status</th>
      <th class="info">Doctor</th>
      <th class="info">Patient</th>
      <th colspan="3" class="active"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultations.each do |consultation| %>
      <tr>
        <td><%= consultation.historic %></td>
        <td><%= consultation.note %></td>
        <td><%= consultation.payment %></td>
        <td><%= consultation.status %></td>
        <td><%= consultation.doctor.name %></td>
        <td><%= consultation.patient.name %></td>
        <td><%= link_to 'Ver', consultation %></td>
        <td><%= link_to 'Editar', edit_consultation_path(consultation) %></td>
        <td><%= link_to 'Excluir', consultation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Consulta', new_consultation_path %>

app/views/consultations/new.html.erb
<h1>New Consultation</h1>

<%= render 'form', consultation: @consultation %>
<br>
<%= link_to 'Back', consultations_path, class: "btn btn-danger" %>

app/views/consultations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Historic:</strong>
  <%= @consultation.historic %>
</p>

<p>
  <strong>Note:</strong>
  <%= @consultation.note %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @consultation.payment %>
</p>

<p>
  <strong>Status:</strong>
  <%= @consultation.status %>
</p>

<p>
  <strong>Doctor:</strong>
  <%= @consultation.doctor %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @consultation.patient %>
</p>

<%= link_to 'Edit', edit_consultation_path(@consultation) %> |
<%= link_to 'Back', consultations_path %>